# 基础镜像
FROM elasticsearch:7.17.6
# author
MAINTAINER WangZhen

COPY ./elasticsearch-analysis-ik /usr/share/elasticsearch/plugins/elasticsearch-analysis-ik

ENV TZ=Asia/Shanghai

RUN ln -sf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone