# 基础镜像
FROM mysql/mysql-server:8.0.31
# author
MAINTAINER WangZhen

ENV TZ=Asia/Shanghai

RUN ln -sf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

# 执行sql脚本
COPY ./db/blog.sql /docker-entrypoint-initdb.d/